[package]
name = "hayaku-path"
version = "0.1.0"
authors = ["nokaa <nokaa@cock.li>"]

[dependencies]
log = "0.3.6"
quick-error = "1.1.0"
regex = "0.1.80"
serde_derive = "0.8.19"
serde_json = "0.8.3"

[dependencies.hayaku-http]
path = "../hayaku-http"
